### ISSUE TITLE
can you give me a example for  “genericity”

### ISSUE THREAD

**Issue by hzj61002963** [wurstscript/WurstSetup#10]
my English is not so good.And I didn't learn other computer language except jass.
can you give me a example like "remove or save any handle". thank you! 
i know it is so troublesome
but china has little people learn this 
so please T﹏T

**Comment by Frotty** [comment]
Not sure what you mean by 
> "remove or save any handle"

Something like this?
```
class MyClass

let map = new HashMap<unit, MyClass>()
```
