### ISSUE TITLE
wurstpack_compiler.zip Not found at runnning Install WurstScript

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstSetup#12]
Where to start for error searching?
![1](https://user-images.githubusercontent.com/640169/40580786-c9939bfc-6146-11e8-823a-d6126ba9dfe2.PNG)
![2](https://user-images.githubusercontent.com/640169/40580787-cb161220-6146-11e8-8489-2900fa828f8c.PNG)

**Comment by Frotty** [comment]
check if the .zip actually exists. Could be a permission problem, or the file is blocked by some antivir.

**Comment by Krypt0n** [comment]
Where should the file supposed to be? 
Could not find it via search, no blocks has been logged so far.

**Comment by Frotty** [comment]
Glad to hear 👍 
Make sure to star our main repo if you enjoy wurst 🍺
