### ISSUE TITLE
Wurst Setup doesn't recall my Game Path (Windows 7 x64)

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstSetup#18]
Whenever I open the wurstsetup - even if I haven't recently updated wurstsetup, I need to reselect Game Path

![image](https://user-images.githubusercontent.com/1418966/42511853-eb76119c-844a-11e8-99d6-463206b5987d.png)

This is a shame because Game Path really is needed

Should the Game Path not discover default directories like `Program Files (x86)\Warcraft III` anyway?

**Comment by Frotty** [comment]
> This is a shame because Game Path really is needed

For what? The game path is only needed for the runmap command.

> Should the Game Path not discover default directories like Program Files (x86)\Warcraft III anyway?

The game path detection is done by reading the windows registry. If the registry entries don't exist or you're not on windows, the path won't be detected.

**Comment by Cokemonkey11** [comment]
> For what?

For generating a good project environment when creating a new project. If you forget it, you have to go fill it in later, which requires either copy-pasting from an existing project metadata file, or understanding the schema. Both are not that user-friendly.

Maybe a good solution is to always create that metadata file, and instead use a commented-out GamePath configuration, with a comment that says what it's for and why it's commented out?

> The game path detection is done by reading the windows registry

Which registry value is checked? It seems that 1.29+ don't set any value that points to `Program Files (x86)\Warcraft III\` in `HKEY_CURRENT_USER\Software\Blizzard Entertainment\Warcraft III`

**Comment by Frotty** [comment]
> For generating a good project environment when creating a new project. If you forget it, you have to go fill it in later, which requires either copy-pasting from an existing project metadata file, or understanding the schema. Both are not that user-friendly.

No, it simply requires importing the existing project and updating it with the gamepath.

Which registry value is checked? It seems that 1.29+ don't set any value 

Does it write any?

**Comment by Cokemonkey11** [comment]
> No, it simply requires importing the existing project and updating it with the gamepath.

I hadn't thought of that. Now that I think of it, I didn't fully realize the value of `import` function.

I suspect this will naturally clear itself up as project dependencies become more widely used.

> Does it write any?

It writes a path in `Documents` for maps, which is not that useful. It seems that the installer also writes a path, but that's under a different key. There could be more. I only had a quick ctrl+f through the registry.

**Comment by Frotty** [comment]
> I hadn't thought of that. Now that I think of it, I didn't fully realize the value of import function.
 I suspect this will naturally clear itself up as project dependencies become more widely used.

Yea, probably needs to be more apparent to the user.

> It writes a path in Documents for maps, which is not that useful. It seems that the installer also writes a path, but that's under a different key. There could be more. I only had a quick ctrl+f through the registry.

I guess a detection via path could be useful also, but limited.

**Comment by Cokemonkey11** [comment]
> I guess a detection via path could be useful also, but limited.

Do you mean by just checking the directory exists? I think that's perfectly reasonable

**Comment by Frotty** [comment]
> Do you mean by just checking the directory exists? I think that's perfectly reasonable

Yes, but many users (including me) install wc3 in non-default directories.

**Comment by Cokemonkey11** [comment]
I think if you can infer path from registry then that's better.

But, if you can't, but you can say that even just half of users are installing in default directory, then I think detecting it is worthwhile

**Comment by Frotty** [comment]
default install paths are now also checked.

**Comment by Cokemonkey11** [comment]
Seen this working today :)
