### ISSUE TITLE
Adding Game Path quietly screws up Project root

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstSetup#19]
Step 1: open wurstsetup

![image](https://user-images.githubusercontent.com/1418966/42511907-125ae968-844b-11e8-9751-d7ab74da5e54.png)

Step 2: select a Game path

![image](https://user-images.githubusercontent.com/1418966/42511937-26e196b6-844b-11e8-976b-89a5c8424198.png)

Step 3: type in a Project name

![image](https://user-images.githubusercontent.com/1418966/42511955-35eeefc8-844b-11e8-9252-6e9f34004bd0.png)

Observe that Project root absolute path has been changed even though only the project name wanted to be adjusted

**Comment by Cokemonkey11** [comment]
When executing the same steps above, the latest version adds an extra `.\`:

![image](https://user-images.githubusercontent.com/1418966/42757269-4b972786-88f7-11e8-8298-cd5d75400ba9.png)

However, this seems to at least work properly if you hit "Create Project"

**Comment by Frotty** [comment]
works as expect I'd say

**Comment by Cokemonkey11** [comment]
ok, good enough for me
