### ISSUE TITLE
possibility to configure specific branch of dependencies in wurst.build

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstSetup#33]
Could we add on option to wurst.build to configure dependencies  branch
so instead of getting master branch we get a branch "test" from the git e.g.

```
---
projectName: Test
dependencies:
- https://github.com/Krypt0n/WurstStdlib2.git -b test --single-branch
```

**Comment by Frotty** [comment]
Yes, specific revision hashes and branches are coming soon 😺
