### ISSUE TITLE
Fails to access a unix path when running in msys2

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstSetup#38]
```
$ pwd
/c/Users/user/workspace2/EscapeTheCrab

$ grill install
Error: Unable to access jarfile /home/User/.wurst/WurstSetup.jar

$ which grill
/c/users/user/.wurst/grill
```

**Comment by Frotty** [comment]
Grill resolves the user home `~`. Apparently it's not set correctly for msys2 or so?
Not sure what I could do here.

**Comment by Cokemonkey11** [comment]
As `grill` is in the same directory as WurstSetup, I recommend it discover its own fs path, and use that.

Msys2 has a separate home directory. It's virtual, and maps to `C:\msys64\home\User`.

So the second half of the problem is that the tooling that installs `.wurst` to home directory works slightly differently than grill does.

**Comment by Frotty** [comment]
Status?
