### ISSUE TITLE
`grill help` doesn't provide any help text

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstSetup#41]
```
blake@LAPTOP-ASBN7T4S:~/workspace/the-gorge$ grill help
🔥 Grill warming up..
🔥 Ready. Version: <1.3.1.1-jenkins-WurstSetup-123>
Use one of the following commands: HELP, INSTALL, REMOVE, GENERATE, TEST, BUILD
```

**Comment by Frotty** [comment]
No, that is what the help command displays. https://github.com/wurstscript/WurstSetup/blob/4c136f8532c977d819dafb0e15705cea4ae1f27c/src/main/kotlin/file/SetupApp.kt#L59

**Comment by Cokemonkey11** [comment]
@Frotty what an awful help message. You should be ashamed of yourself
