### ISSUE TITLE
fresh grill install does not have execute permissions set

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstSetup#44]
```
blake@LAPTOP-ASBN7T4S:~/workspace$ grill
-bash: /home/blake/.wurst/grill: Permission denied
```

```
blake@LAPTOP-ASBN7T4S:~/workspace$ ls -latr ~/.wurst
...
-rw-rw-rw- 1 user user       55 Aug 25 19:17 grill
```

**Comment by Frotty** [comment]
PR with unix executable flag?

**Comment by Cokemonkey11** [comment]
@Frotty happy to contribute, sure.

I took a quick search for `grill`, but I don't see where it gets created. Can you provide a pointer?

**Comment by Cokemonkey11** [comment]
Found https://github.com/wurstscript/WurstSetup/blob/b5773c7336b0d7a3405ea4cb8b8caca3b4ae38ff/src/main/kotlin/ui/SetupUpdateDialog.kt#L55 but it's unclear if code should be added here or somewhere else.

**Comment by Frotty** [comment]
actually part of wurst and not grill 😄 
https://github.com/wurstscript/WurstScript/tree/master/Wurstpack/wurstscript

**Comment by Cokemonkey11** [comment]
Looks like grill is checked-in with the right perms:

```
user@LAPTOP-ASBN7T4S:~/workspace/WurstScript/Wurstpack/wurstscript$ ls -latr
total 1408
-rwxrwxrwx 1 user user    490 Aug 26 18:31 wrapper_config.toml
-rwxrwxrwx 1 user user 375296 Aug 26 18:31 wurstscript.exe
drwxrwxrwx 1 user user   4096 Aug 26 18:33 ..
-rwxrwxrwx 1 user user 455365 Aug 26 18:33 blizzard.j
-rwxrwxrwx 1 user user 345751 Aug 26 18:33 common.j
-rwxrwxrwx 1 user user     55 Aug 26 18:33 grill
drwxrwxrwx 1 user user   4096 Aug 26 18:33 .
-rwxrwxrwx 1 user user 254976 Aug 26 18:33 grill.exe
```

Presumably this is jgit 🖕  - I'll dig a bit

**Comment by Cokemonkey11** [comment]
I found https://bugs.eclipse.org/bugs/show_bug.cgi?id=424395 but it looks like it's been fixed in 3.6.x, and we're using [5.4.0](https://github.com/wurstscript/WurstSetup/blob/master/build.gradle#L31).

Any ideas? We could just change the file mode after download but it seems fragile

**Comment by Frotty** [comment]
> We could just change the file mode after download but it seems fragile

I tried that. You should check whether that works at all though.

**Comment by Cokemonkey11** [comment]
> I tried that. You should check whether that works at all though.

It works when I do it manually.

LGTM

**Comment by Frotty** [comment]
yea u should delete .wurst folder and reinstall try again

**Comment by Cokemonkey11** [comment]
```
user@LAPTOP-ASBN7T4S:~$ rm -r .wurst/
user@LAPTOP-ASBN7T4S:~$ java -jar workspace/WurstSetup.jar install wurstscript
🔥 Grill warming up..
WurstScript is not currently installed.
🔥 Ready. Version: <1.3.1.1-jenkins-WurstSetup-123>
⚠️ No wurst.build configuration file at current location.
🌭 Installing WurstScript..
        Update available!
⏬ Downloading Wurst4cript..   $  s  g  6     4                        r
        📥 (35MB)
        📦 Extracting..
✔ Installed WurstScript
user@LAPTOP-ASBN7T4S:~$ grill help
-bash: /home/user/.wurst/grill: Permission denied
user@LAPTOP-ASBN7T4S:~$ ls -latr .wurst/
...
-rw-rw-rw- 1 user user       55 Aug 26 18:54 grill
```

No luck. Did I need to wait longer?

**Comment by Frotty** [comment]
> <1.3.1.1-jenkins-WurstSetup-123>

is old version

**Comment by Cokemonkey11** [comment]
I need to fetch new setup before it will download latest wurstscript?

**Comment by Frotty** [comment]
that is the version of the setup?!

**Comment by Cokemonkey11** [comment]
Thanks! Can confirm this is fixed
