### ISSUE TITLE
how to setup in China

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstSetup#5]
_From @zhongying1995 on February 17, 2018 3:41_

when i setup the WurstSetup.jar,it say Ready version:1.1.4.0-jenkins-WurstSetup-52    Server offline.All update functionality disabled. 
i had used the Lantern ,a VNP to Surf the foreign Internet(i am chinese),but can not setup Wurst.
So,what should i do?

_Copied from original issue: wurstscript/WurstScript#622_

**Comment by peq** [comment]
If you have full access to Github, you could also build everything from source.

Does it make a difference whether we host the files via https or http?

**Comment by zhongying1995** [comment]
thanks,i had solve it just now.Maybe the reason is my network speed is so low.........you know,sometimes it is bad for chinese use the softwares not from china.
when i tried to setup it many times,i successed!

**Comment by Frotty** [comment]
@peq http fallback has been in place for some time now.
@zhongying1995 cool. I will close the issue then 👍
