### ISSUE TITLE
How can I downgrade compiler?

### ISSUE THREAD

**Issue by tester1101** [wurstscript/WurstSetup#66]
### [important!!] I'm using pre1.29 version.

My compiler version was 1240 and it worked well in vscode. but I made a mistake and compiler was updated to 1324.
Of course, this updating make compiling impossible for me.
How can I downgrade compiler to 1240?

**Comment by Frotty** [comment]
Other than compiling the specific commit yourself there is no way to downgrade. What is your issue with the latest version?

**Comment by tester1101** [comment]
In conclusion, after I rebooted computer, all problems are gone.

I'm sorry, I was too confused and posted this without trying anything possible.
At the moment after updating compiler, I tried to compile in vscode for checking whether updating make problems and I encountered more than hundreds errors.
So I panicked and posted this like a fool.
It's very shame on me.
